# Packages ---------------------------------------------------------------------
library(dplyr)
library(readr)

# Experimental data analysis

# Load data
data_clean <- readRDS("_SharedFolder_datagotchi-santé/data/clean/datagotchi-sante_clean.rds")
data_raw <- haven::read_sav("_SharedFolder_datagotchi-santé/data/raw/data_raw.sav")  %>% 
  filter(code == "complete")

# Check missing values ---------------------------------------------------------
missing_values <- colSums(is.na(data_clean))
missing_values[missing_values > 0]

# Remove observations without score (because of NA in the questionnaire)
data <- data_clean %>%
  filter(!is.na(data_clean$score_norm))

# Check missing values
missing_values <- colSums(is.na(data))
missing_values[missing_values > 0]

# Aperçu des valeurs pour chaque variable
summary(data)

# Comparaisons variables clean et raw ------------------------------------------
names_clean_r <- names(data_clean)
names_raw_r <- names(data_raw)

names_clean_codebook <- c(
  "ses_genre",
  "ses_sexual_orientation",
  "ses_age",
  "ses_age_group",
  "ses_langue_maternelle",
  "ses_occupation_self_employed",
  "ses_occupation_salaried_work",
  "ses_occupation_retired",
  "ses_occupation_unemployed",
  "ses_occupation_student",
  "ses_occupation_caregiver",
  "ses_occupation_parent",
  "ses_occupation_handicap",
  "ses_occupation_multiple_job_self_employment",
  "ses_occupation_multiple_job_salaried",
  "ses_occupation_unemployed_social_assistance",
  "ses_emploi",
  "ses_travail_management",
  "ses_travail_finance",
  "ses_travail_natural_sciences",
  "ses_travail_health",
  "ses_travail_education_law_government",
  "ses_travail_art_sport",
  "ses_travail_sales_services",
  "ses_travail_trades_transport",
  "ses_travail_transport",
  "ses_travail_manufacturing",
  "ses_travail_other",
  "ses_heures_travail",
  "ses_heures_teletravail",
  "ses_revenu",
  "ses_percep_revenu",
  "ses_education",
  "ses_pays_origine",
  "ses_origines_ethniques",
  "ses_religion",
  "ses_religiosite",
  "ses_enfants",
  "ses_enfants_bin",
  "ses_marital_status",
  "ses_married_bin",
  "ses_single_bin",
  "ses_poids",
  "ses_code_postal",
  "ses_travail_deplacement",
  "ses_urban_rural",
  "ses_habitation",
  "ses_province_",
  "lifestyle_pets",
  "lifestyle_act_physique",
  "lifestyle_freq_physique_",
  "lifestyle_transport",
  "lifestyle_car_model",
  "lifestyle_consumption",
  "lifestyle_coffee",
  "lifestyle_meat",
  "lifestyle_alcool_pref",
  "lifestyle_smoking_freq",
  "lifestyle_cannabis",
  "lifestyle_hunting",
  "lifestyle_fishing",
  "lifestyle_motorized",
  "lifestyle_friends_activity",
  "lifestyle_volunteer",
  "lifestyle_museum",
  "lifestyle_nature_may_september",
  "lifestyle_nature_october_april",
  "lifestyle_movie_pref",
  "lifestyle_style",
  "lifestyle_style_other",
  "lifestyle_music_pref",
  "lifestyle_temps_ecran_semaine_travail",
  "lifestyle_temps_ecran_finsemaine_travail",
  "lifestyle_temps_ecran_semaine_loisir",
  "lifestyle_temps_ecran_finsemaine_loisir",
  "bien_etre_general_health",
  "bien_etre_felt_happy",
  "bien_etre_interested_in_life",
  "bien_etre_satisfied_with_life",
  "bien_etre_important_contribution_society",
  "bien_etre_sense_belonging_community",
  "bien_etre_society_becomes_better_place",
  "bien_etre_people_fundamentally_good",
  "bien_etre_society_makes_sense",
  "bien_etre_like_personality",
  "bien_etre_handling_responsibilities",
  "bien_etre_warm_relationships_with_people",
  "bien_etre_better_person",
  "bien_etre_able_express_opinions",
  "bien_etre_life_has_meaning",
  "bien_etre_pleasure_doing_things",
  "bien_etre_sad",
  "bien_etre_nervous",
  "bien_etre_worries",
  "bien_etre_stress_vie",
  "bien_etre_chronic_problems",
  "bien_etre_asthma",
  "bien_etre_copd",
  "bien_etre_sleep_apnea",
  "bien_etre_fibromyalgia",
  "bien_etre_joint_problems",
  "bien_etre_back_pain",
  "bien_etre_osteoporosis",
  "bien_etre_hypertension",
  "bien_etre_cholesterol_lipids",
  "bien_etre_celiac_disease",
  "bien_etre_instestinal_disease",
  "bien_etre_heart_disease",
  "bien_etre_stroke_disorders",
  "bien_etre_diabetes",
  "bien_etre_cancer",
  "bien_etre_thyroid_problems",
  "bien_etre_alzheimers_dementia",
  "bien_etre_chronic_fatigue",
  "bien_etre_renal_failure",
  "bien_etre_liver_disease",
  "bien_etre_abdomen_ulcers",
  "bien_etre_allergies",
  "comp_sante_focus_attention_present",
  "comp_sante_learn_live_strengths_weaknesses",
  "comp_sante_congratulate_myself_successes",
  "comp_sante_try_love_myself_as_i_am",
  "comp_sante_consider_abilities_make_schedule",
  "comp_sante_find_comfort_people_around_listen",
  "attention_check_ok",
  "comp_sante_do_activities_enjoy_keep_life_active",
  "comp_sante_have_healthy_diet",
  "comp_sante_do_exercises_relax",
  "comp_sante_acknowledge_challenges_difficulties",
  "comp_sante_engage_supportive_comforting_self_talk",
  "comp_sante_remind_failure_challenge_part_human_experience",
  "comp_sante_sleep_quality",
  "comp_sante_chronotype",
  "comp_sante_sleep_pattern_satisfaction",
  "comp_sante_sleep_problem_interfere_daily_functioning",
  "comp_sante_fruit_vegetables_servings",
  "comp_sante_alcohol_freq",
  "comp_sante_cannabis_freq",
  "comp_sante_cannabis_freq_bin",
  "comp_sante_amphetamines_freq",
  "comp_sante_amphetamines_freq_bin",
  "comp_sante_tobacco_freq",
  "comp_sante_tobacco_freq_bin",
  "comp_sante_physical_activity_high_intensity",
  "comp_sante_physical_activity_moderate_intensity",
  "comp_sante_physical_activity_low_intensity",
  "enviro_work_lack_time_for_tasks",
  "enviro_work_one_task_at_a_time",
  "enviro_work_contradictory",
  "enviro_work_heavy_workload",
  "enviro_work_frequently_interrupted",
  "enviro_work_lot_of_responsibility",
  "enviro_work_forced_overtime",
  "enviro_work_objectives_are_clear",
  "enviro_work_physical_effort",
  "enviro_work_became_demanding",
  "enviro_work_require_concentration",
  "enviro_work_workload_too_heavy",
  "enviro_travail_freedom_work",
  "enviro_travail_influence_amount_work",
  "enviro_travail_decide_break",
  "enviro_travail_influence_decisions_work",
  "enviro_travail_influence_do_job",
  "enviro_travail_colleagues_sensitive",
  "enviro_travail_support_from_colleagues",
  "enviro_travail_ask_colleagues_for_help",
  "enviro_travail_task_distributed_fairly",
  "enviro_travail_superior_conflict_resolution",
  "enviro_travail_support_from_superior",
  "enviro_travail_superior_competent_planning",
  "enviro_travail_superior_priority_job_satisfaction",
  "enviro_travail_times_discuss_difficulties",
  "enviro_travail_superior_listens",
  "enviro_travail_superior_work_together",
  "enviro_quartier_safe_bike_paths",
  "enviro_quartier_fresh_fruits_and_vegetables",
  "enviro_quartier_friendly_neighborhood",
  "enviro_quartier_nice_looking_neighborhood",
  "enviro_quartier_accessible_sports_facilities",
  "enviro_quartier_fast_food",
  "enviro_quartier_green_spaces",
  "enviro_quartier_safe_neighborhood",
  "enviro_quartier_places_for_socializing",
  "enviro_quartier_noisy_polluted_neighborhood",
  "quartier_opportunities_health",
  "quartier_satisfaction",
  "service_sante_famille_general",
  "service_sante_specialist",
  "service_sante_nurse_practitioner",
  "service_sante_other",
  "service_sante_none",
  "service_sante_sexual_satisfaction",
  "service_sante_mental_consult",
  "service_sante_mental_famille_general",
  "service_sante_mental_psychiatrist",
  "service_sante_mental_psychologue",
  "service_sante_mental_nurse",
  "service_sante_mental_social_worker",
  "service_sante_mental_other",
  "service_sante_mental_none",
  "service_sante_mental_other_text",
  "valeurs_respect_elders",
  "valeurs_religiosity",
  "valeurs_care_for_others",
  "attention_check_2",
  "valeurs_equal_opportunity_for_everyone",
  "valeurs_curious",
  "valeurs_takes_risks",
  "valeurs_having_fun",
  "valeurs_important_being_successful",
  "valeurs_important_being_in_charge",
  "valeurs_organized",
  "valeurs_extraverted_enthusiastic",
  "valeurs_critical_quarrelsome",
  "valeurs_dependable_self_disciplined",
  "valeurs_anxious_easily_upset",
  "valeurs_open_experiences_complex",
  "valeurs_reserved_quiet",
  "valeurs_sympathetic_warm",
  "valeurs_disorganized_careless",
  "valeurs_calm_emotionally_stable",
  "valeurs_conventional_uncreative",
  "climate_worry_climate_change",
  "climate_worry_future",
  "climate_worry_climate_people",
  "comport_socio_people_count_on",
  "comport_socio_emotional_security",
  "comport_socio_life_decision",
  "comport_socio_skills_relationship",
  "comport_socio_group_beliefs",
  "comport_socio_immediate_friends",
  "comport_socio_friends_dispo",
  "comport_socio_success_poly",
  "comport_socio_child_poly_parent",
  "comport_socio_poly_cheat",
  "comport_socio_poly_relation",
  "discrimination_gender",
  "discrimination_gender_expression",
  "discrimination_ethnicity_culture",
  "discrimination_race",
  "discrimination_physical_appearance",
  "discrimination_religion",
  "discrimination_sexual_orientation",
  "discrimination_age",
  "discrimination_disability",
  "discrimination_language",
  "discrimination_other",
  "discrimination_never",
  "political_behaviour_turnout_prob",
  "political_behaviour_voted_2021",
  "political_behaviour_vote_choice_2021",
  "political_behaviour_vote_intent",
  "political_behaviour_vote_intent_certainty",
  "political_behaviour_prob_support_PLC",
  "political_behaviour_prob_support_PCC",
  "political_behaviour_prob_support_BQ",
  "political_behaviour_prob_support_PPC",
  "political_behaviour_prob_support_NPD",
  "political_behaviour_prob_support_PVC",
  "political_behaviour_irc_PLC",
  "political_behaviour_irc_PCC",
  "political_behaviour_irc_BQ",
  "political_behaviour_irc_PPC",
  "political_behaviour_irc_NPD",
  "political_behaviour_irc_PVC",
  "political_behaviour_left_right",
  "ai_trust_enough_disclosure",
  "ai_take_care_protect_personal_data",
  "attention_check_2_ok",
  "ai_government_use_numeric_data_public_good",
  "best_canadian_book",
  "best_canadian_album",
  "best_canadian_movie",
  "best_canadian_newspaper",
  "know_french_media_personality",
  "know_french_singer",
  "know_french_actor",
  "know_french_writer",
  "know_english_media_personality",
  "know_english_singer",
  "know_english_actor",
  "know_english_writer",
  "french_speaking_friends",
  "english_speaking_friends",
  "other_language_speaking_friends",
  "french_speaking_skills",
  "english_speaking_skills",
  "exp_1",
  "exp_2"
)

raw_codebook <- read_csv("codebook_sante.csv")
names_raw_codebook <- raw_codebook[[3]]

diff_clean_r_codebook <- setdiff(names_clean_r, names_clean_codebook)
print("Variables présentes dans data_clean R mais pas dans le codebook :")
print(diff_clean_r_codebook)

diff_clean_codebook_r <- setdiff(names_clean_codebook, names_clean_r)
print("Variables présentes dans le codebook mais pas dans data_clean R :")
print(diff_clean_codebook_r)

diff_raw_r_codebook <- setdiff(names_raw_r, names_raw_codebook)
print("Variables présentes dans data_raw R mais pas dans le codebook :")
print(diff_raw_r_codebook)

diff_raw_codebook_r <- setdiff(names_raw_codebook, names_raw_r)
print("Variables présentes dans le codebook mais pas dans data_raw R :")
print(diff_raw_codebook_r)
