class CreateFeatureConfig:
    # Versioning
    RUN_TYPE = "REAL_FOLDER_NAME"  # SANDBOX_FOLDER_NAME or REAL_FOLDER_NAME
    CODEBOOK_VERSION = "frozen_codebook_july_25.csv"
    CODEBOOK_OBSERVABILITY_COL_NAME = "C.CODEBOOK_OBSERVABILITY_COL_V2" # C.CODEBOOK_OBSERVABILITY_COL or C.CODEBOOK_OBSERVABILITY_COL_V2

    # Target encoding
    TARGET_ENCODING_SINGLE_NOMINAL = True
    TARGET_ENCODING_MULTIPLE_NOMINAL = True
    TARGET_NAME = "C.TARGET_SCORE_TOT"

